<?php
/**
 * @name BillerTest.php
 * @author Richard Rowley
 * @license GPL V3 or above
 * Created: 20181103
 */

use Inc\Claz\Biller;
use PHPUnit\Framework\TestCase;

/**
 * Class BillerTest
 */
class BillerTest extends TestCase
{
    public  function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testGetAll()
    {
        $rows = Biller::get_all();
        $this->assertNotEmpty($rows);
    }

}
