<?php

use Inc\Claz\Biller;

/**
 * @name BillerTest.php
 * @author fearl
 * @license GPL V3 or above
 * Created: 11/3/2018
 */

use PHPUnit\Framework\TestCase;

class BillerTest extends TestCase
{
    public  function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testGetAll()
    {
        $rows = Biller::get_all();
        $this->assertNotEmpty($rows);
    }

}
